### ISSUE TITLE
Require steps to run the applicatio

### ISSUE THREAD

**Issue by NagarajMani** [mmulazzani/SHPF#1]
Hello,

Please provide some steps to setup, configure and run the app. 

Thanks,

**Comment by schmiedecker** [comment]
Should be exemplified in usage.sample.php.

You can also read the paper: https://www.sba-research.org/wp-content/uploads/publications/shpf_extendedPreprint.pdf

**Comment by mmulazzani** [comment]
I'll close this, please open a new issue if you still have questions.
